name: Storyboard
description: Suggest a new use case or access pattern.
title: "[STORYBOARD]: "
labels: ["documentation"]
projects: ["gavinjalberghini/9"]
assignees:
  - gavinjalberghini
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a user story!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: user_story
    attributes:
      label: Please provide your user story.
      description: What new use case or access pattern would you like to see?
      placeholder: Insert awesome user story here 🎉
      value: "As a [role],\nI want [an action or feature],\nSo that [a reason or benefit]."
    validations:
      required: true
  - type: textarea
    id: breakdown
    attributes:
      label: Tasks to accomplish user story.
      description: In as much description as possible, provide a list of high level technical tasks that would be required to accomplish the above. 
      placeholder: Insert your task list here. These will become direct references from feature requests.
      value: "- [ ] Task 1: \n- [ ] Task 2: \n- [ ] Task 3: "
    validations:
      required: true