name: Semantic Versioning

on: 
  push:
    branches:
      - main

jobs:
  update-semantic-version:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
         fetch-depth: 0

      - name: Documentation Version
        id: docs-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          change_path: "docs"
          tag_prefix: "v"
          major_pattern: "/^(break)/"
          minor_pattern: "/^(docs|style)/"
          version_format: "v${major}.${minor}.${patch}"
          bump_each_commit: true

      - name: Infrastructure Version
        id: infra-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: "v"
          major_pattern: "/^(break)/"
          minor_pattern: "/^(feat|fix|chore|refactor)/"
          version_format: "v${major}.${minor}.${patch}"
          bump_each_commit: true
