name: Semantic Versioning

on: 
  push:
    branches:
      - main

jobs:
  release:
    runs-on: [self-hosted, Linux, X64, wsl, desktop-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
         fetch-depth: 0

      - name: Documentation Version
        id: docs-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          change_path: "docs"

      - name: Infrastructure Version
        id: infra-version
        uses: paulhatch/semantic-version@v5.4.0
        with:
          change_path: "config"
