name: Semantic Versioning

on: 
  push:
    branches:
      - main

jobs:
  release:
    runs-on: [self-hosted, Linux, X64, wsl, desktop-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        with:
          extra_plugins: |
            @semantic-release/git
            @semantic-release/exec
            @semantic-release/changelog    
