name: Semantic Versioning

on: 
  push:
    branches:
      - main

jobs:
  print-hello-world:
    runs-on: [self-hosted, Linux, X64, wsl, desktop-1]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print Hello World
        run: echo "Hello, World!"

